<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');
 
jimport('joomla.application.component.controllerform'); 
 
/**
 * Course group Controller
 */
class AFTMSControllerCourseGroup extends JControllerForm
{
	function sendmail()
	{		
    $error = false;
    $post = JFactory::getApplication()->input->post;
    
    $res = $post->get('g-recaptcha-response', null, null);
		if(!$res)
    {
      $return['captcha'] = JText::_('COM_AFTMS_WRONG_CAPTCHA');
      $error=true;
    }

	
			$name = $post->get('name', null, null);
			$email = $post->get('email', null, null);
			$phone = $post->get('phone', null, null);
			$campus = $post->get('campus', null, null);
			$temp = explode( '@alliance-francaise.ca' , $campus, 1);
			$campusName = $temp[0];
			$comment = $post->get('comment', null, null);
			$coursename = $post->get('course_name', null, null);
      
      switch($campus)
      {
        case '1':
          $campusEmail = 'toronto@alliance-francaise.ca';
          $campusName = 'Spadina';
          break;
        
        case '2':
          $campusEmail = 'northyork@alliance-francaise.ca';
          $campusName = 'North York';
          break;
        
        case '3':
          $campusEmail = 'mississauga@alliance-francaise.ca';
          $campusName = 'Mississauga';
          break;
        
        case '4':
          $campusEmail = 'markham@alliance-francaise.ca';
          $campusName = 'Markham';
          break;
        
        case '5':
          $campusEmail = 'oakville@alliance-francaise.ca';
          $campusName = 'Oakville';
          break;
      }
			
			if(empty($name))
			{
				$return['name']= JText::_('COM_AFTMS_NAME_REQUIRED');
        $error=true;
			}
			
      if(empty($email))
			{
				$return['email'] = JText::_('COM_AFTMS_EMAIL_REQUIRED');
        $error=true;
			}
      elseif(!filter_var($email, FILTER_VALIDATE_EMAIL))
			{
				$return['email'] = JText::_('COM_AFTMS_EMAIL_INVALID');
        $error=true;
			}
			
      if(!$error)
			{
		
				$mailer = JFactory::getMailer();
				
				//$sender = array( $email, $name );
        $config = JFactory::getConfig();
        $sender = array( 
            $config->get( 'mailfrom' ),
            $config->get( 'fromname' ) 
        );

        $mailer->setSender($sender);
        
				
				$mailer->addRecipient($campusEmail);
        //$mailer->addRecipient(['florian@alliance-francaise.ca', 'florian.denizot@gmail.com']);
				$mailer->setSubject("Tenez moi au courant de l'ouverture du cours " . $coursename);
				
				$body = '<p> ' . $name . ' wishes to be informed when the course ' . $coursename . ' will be offered in the ' . $campusName . ' campus.<p/>
          <p><b>Contact information</b></p>
          <p>
						'.$name.'<br/>
						'.$email.'<br/>
						'.$phone.'
					</p>
          <p><b>Comments</b></p>
          <p>' . $comment . '</p>
					
					<hr/><br/>
          <p><small>This email was automatically generated by http://www.alliance-francaise.ca.</small></p>
          <p><small><b>AFT Webmaster</b></small></p>';
				
				$mailer->isHTML(true);
				$mailer->Encoding = 'base64';
				$mailer->setBody($body);
				
				$send = $mailer->Send();
				
				if ( $send !== true ) 
        {
					$return['error'] = JText::sprintf('COM_AFTMS_EMAIL_ERROR', $send->__toString());
				}
				else
				{
					$return['success']= JText::_('COM_AFTMS_EMAIL_SUCCESS');
				}
			}
    
		$return["json"] = json_encode($return);
    echo json_encode($return);
	}
}